/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Login.usuarios;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Actividad;
import modelo.Usuario;
import utils.GestionIdiomas;

/**
 *
 * @author JhojanL
 */
public class ConsultasTrabajador extends javax.swing.JFrame {

    private GestionIdiomas gestionIdiomas;
    private Usuario user;
    private Usuario trabajador;
    private String idiomaSistema;
    private DefaultTableModel modelo;

    /**
     * Creates new form Login
     */
    public ConsultasTrabajador(Usuario user, String idiomaSistema) {

        initComponents();
        desactivarPanel();

        this.user = user;
        System.out.println(this.user);
        this.idiomaSistema = idiomaSistema;
        this.trabajador = new Usuario();
        this.jLabelNombreUser.setText(user.getNombre().toUpperCase());
        modelo = new DefaultTableModel();
        cambiarIdioma(idiomaSistema);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelConsultas = new javax.swing.JLabel();
        jLabelAtras = new javax.swing.JLabel();
        jLabelNombreUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanelP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxFiltro = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 62, 169));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelConsultas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultas.setText("CONSULTAS");
        jPanel2.add(jLabelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabelAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jLabelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAtrasMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 23, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 564, 58));

        jLabelNombreUser.setBackground(new java.awt.Color(0, 0, 0));
        jLabelNombreUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNombreUser.setText("USER");
        jPanel1.add(jLabelNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelP.setBackground(new java.awt.Color(255, 255, 255));
        jPanelP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelP.setForeground(new java.awt.Color(255, 255, 255));
        jPanelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo de actividad", "Descripcion", "Horas estimadas", "Estado", "Prioridad"
            }
        ));
        jScrollPane1.setViewportView(tablaConsulta);

        jPanelP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 230));

        jPanel3.add(jPanelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 83, 500, 230));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 67, 520, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupaN.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Tarea completada", "Tarea no completada" }));
        jComboBoxFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Filtrar por:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 138, 518, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jComboBoxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 466, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        busqueda();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAtrasMouseClicked
        this.dispose();
        new indexTrabajador(user, idiomaSistema).setVisible(true);
    }//GEN-LAST:event_jLabelAtrasMouseClicked

    private void jComboBoxFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroActionPerformed

    private void jComboBoxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaActionPerformed
        String itemSeleccionado = jComboBoxIdioma.getSelectedItem().toString();
        cambiarIdioma(itemSeleccionado);
    }//GEN-LAST:event_jComboBoxIdiomaActionPerformed

    public void cambiarIdioma(String idioma) {
        idiomaSistema = idioma;
        gestionIdiomas = new GestionIdiomas(idioma);
        jLabelConsultas.setText(gestionIdiomas.getProperty("consultas").toUpperCase());
//        jLabelCodigoTrabajador.setText(gestionIdiomas.getProperty("codigo_trabajador"));
        //jLabelGuardar.setText(gestionIdiomas.getProperty("guardar"));
        modelo.setColumnCount(0);
        modelo.addColumn(gestionIdiomas.getProperty("tipo_actividad"));
        modelo.addColumn(gestionIdiomas.getProperty("descripcion"));
        modelo.addColumn(gestionIdiomas.getProperty("horas"));
        modelo.addColumn(gestionIdiomas.getProperty("estado"));
        modelo.addColumn(gestionIdiomas.getProperty("prioridad"));
        this.tablaConsulta.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxFiltro;
    private javax.swing.JComboBox<String> jComboBoxIdioma;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAtras;
    private javax.swing.JLabel jLabelConsultas;
    private javax.swing.JLabel jLabelNombreUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelP;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables

    private void busqueda() {

        System.out.println("combo select:"+ jComboBoxFiltro.getSelectedIndex() );
        if (!jComboBoxFiltro.getSelectedItem().equals("")) {

            if (jComboBoxFiltro.getSelectedIndex() == 1) {

                filtrar(1);

            }
            
            if (jComboBoxFiltro.getSelectedIndex() == 2) {

                System.out.println("entre filtro 2");
                filtrar(2);
            }
        }
    }

    private void desactivarPanel() {

        this.jPanelP.setVisible(false);
    }

    private void activarPanel() {

        this.jPanelP.setVisible(true);
    }

//    private void buscarTrabajador() {
//
//        var encontrado = false;
////        var codigo = Integer.parseInt(jTextFieldCodigoTrabajador.getText());
//
////        for (Usuario usuario : usuarios) {
////
////            if (usuario.getCodigo() == codigo && usuario.getRol().equals("Trabajador")) {
////                jLabelNombreTrabajador.setText(usuario.getNombre());
////                encontrado = true;
////                trabajador = usuario;
////                break;
////            }
////        }
//        if (encontrado) {
//
//            activarPanel();
//        } else {
//            this.modelo.setNumRows(0);
//            trabajador = null;
////            jTextFieldCodigoTrabajador.setText("");
//            desactivarPanel();
//            JOptionPane.showMessageDialog(rootPane,
//                    gestionIdiomas.getProperty("mensaje_codT_noEncontrado"),
//                    gestionIdiomas.getProperty("titulo_error"),
//                    JOptionPane.ERROR_MESSAGE);
//
//        }
//
//    }
    private void muestraValores() {

        if (trabajador != null) {

            for (int i = 0; i < trabajador.getActividad().size(); i++) {
                String info[] = new String[5];
                info[0] = trabajador.getActividad().get(i).getTipo();
                info[1] = trabajador.getActividad().get(i).getDescripcion();
                info[2] = "" + trabajador.getActividad().get(i).getHoras();
                info[3] = trabajador.getActividad().get(i).getEstado();
                info[4] = "" + trabajador.getActividad().get(i).getPrioridad();
                modelo.addRow(info);

            }
        }
    }

    private void filtrar(int filtro) {

        if (filtro == 1) {
            
            modelo.setNumRows(0);
            for (int i = 0; i < user.getActividad().size(); i++) {

                System.out.println(user.getActividad().get(i).getEstado() + " es igual a Completada");

                if (user.getActividad().get(i).getEstado().equals("Completada")) {
                    System.out.println("entre al if");
                    String info[] = new String[5];
                    info[0] = user.getActividad().get(i).getTipo();
                    info[1] = user.getActividad().get(i).getDescripcion();
                    info[2] = "" + user.getActividad().get(i).getHoras();
                    info[3] = user.getActividad().get(i).getEstado();
                    info[4] = "" + user.getActividad().get(i).getPrioridad();
                    modelo.addRow(info);
                    activarPanel();

                }
            }

        }
        if (filtro == 2) {
            modelo.setNumRows(0);
            for (int i = 0; i < user.getActividad().size(); i++) {

                System.out.println(user.getActividad().get(i).getEstado() +" es igual a No completada");
                if (user.getActividad().get(i).getEstado().equals("No completada")) {
                    
                   
                    String info[] = new String[5];
                    info[0] = user.getActividad().get(i).getTipo();
                    info[1] = user.getActividad().get(i).getDescripcion();
                    info[2] = "" + user.getActividad().get(i).getHoras();
                    info[3] = user.getActividad().get(i).getEstado();
                    info[4] = "" + user.getActividad().get(i).getPrioridad();
                    modelo.addRow(info);
                    activarPanel();
                }
            }

        }
    }

}
