/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.util.ArrayList;
import modelo.Actividad;
import modelo.Usuario;
import utils.GestionIdiomas;

/**
 *
 * @author Estudiante
 */
public class indexTrabajador extends javax.swing.JFrame {

    private GestionIdiomas gestionIdiomas;
    private Usuario user;
    private String idiomaSistema;

    /**
     * Creates new form Login
     */
    public indexTrabajador(Usuario user, String idiomaSistema) {

        initComponents();

        this.user = user;
        System.out.println(this.user);
        this.idiomaSistema=idiomaSistema;
        this.jLabelNombreUser.setText(user.getNombre().toUpperCase());
        cambiarIdioma(idiomaSistema);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelNombreUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabelSeleccionaAccion = new javax.swing.JLabel();
        jPanelConsultas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelConsultas = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 62, 169));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBienvenido.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenido.setText("BIENVENIDO");
        jPanel2.add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 19, -1, -1));

        jLabelNombreUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelNombreUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUser.setText("USER");
        jPanel2.add(jLabelNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 19, 153, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleadoB.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 45, -1));

        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 19, -1, -1));

        jLabelLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Salir");
        jPanel2.add(jLabelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 15, -1, 28));

        jLabelSeleccionaAccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSeleccionaAccion.setText("Selecciona una accion a realizar:");

        jPanelConsultas.setBackground(new java.awt.Color(42, 62, 169));
        jPanelConsultas.setPreferredSize(new java.awt.Dimension(170, 49));
        jPanelConsultas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseMoved(evt);
            }
        });
        jPanelConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseExited(evt);
            }
        });
        jPanelConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jPanelConsultas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, 27));

        jLabelConsultas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultas.setText("Consultas");
        jPanelConsultas.add(jLabelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 11, 72, 27));

        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jComboBoxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSeleccionaAccion)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabelSeleccionaAccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jPanelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jPanelConsultasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseMoved
        jPanelConsultas.setBackground(new Color(67, 91, 220));
    }//GEN-LAST:event_jPanelConsultasMouseMoved

    private void jPanelConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseExited
        jPanelConsultas.setBackground(new Color(42,62,169));
    }//GEN-LAST:event_jPanelConsultasMouseExited

    private void jPanelConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseClicked
        this.dispose();
        new ConsultasTrabajador(user, idiomaSistema).setVisible(true);
    }//GEN-LAST:event_jPanelConsultasMouseClicked

    private void jComboBoxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaActionPerformed
        String itemSeleccionado = jComboBoxIdioma.getSelectedItem().toString();
        cambiarIdioma(itemSeleccionado);
    }//GEN-LAST:event_jComboBoxIdiomaActionPerformed

    public void cambiarIdioma(String idioma) {
        gestionIdiomas = new GestionIdiomas(idioma);
        jLabelBienvenido.setText(gestionIdiomas.getProperty("bienvenido"));
        jLabelLogout.setText(gestionIdiomas.getProperty("salir"));
        jLabelSeleccionaAccion.setText(gestionIdiomas.getProperty("selecciona_accion"));
        jLabelConsultas.setText(gestionIdiomas.getProperty("consultas"));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelConsultas;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelNombreUser;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelSeleccionaAccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelConsultas;
    // End of variables declaration//GEN-END:variables

}
