/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.util.ArrayList;
import modelo.Actividad;
import modelo.Usuario;
import utils.GestionIdiomas;

/**
 *
 * @author Estudiante
 */
public class indexSupervisor extends javax.swing.JFrame {

    private GestionIdiomas gestionIdiomas;
    private Usuario user;
    private String idiomaSistema;

    /**
     * Creates new form Login
     */
    public indexSupervisor(Usuario user, String idiomaSistema) {

        initComponents();

        this.user = user;
        this.idiomaSistema=idiomaSistema;
        this.jLabelNombreUser.setText(user.getNombre().toUpperCase());
        cambiarIdioma(idiomaSistema);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelNombreUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabelSeleccionaAccion = new javax.swing.JLabel();
        jPanelRegistrarActividades = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelRegistrarActividades = new javax.swing.JLabel();
        jPanelConsultas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelConsultas = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 62, 169));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBienvenido.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenido.setText("BIENVENIDO");
        jPanel2.add(jLabelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabelNombreUser.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelNombreUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreUser.setText("USER");
        jPanel2.add(jLabelNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 153, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toma-de-decisiones.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 15, 45, -1));

        jLabelSalir.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 19, -1, -1));

        jLabelLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Salir");
        jPanel2.add(jLabelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 15, -1, 28));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 523, 73));

        jLabelSeleccionaAccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSeleccionaAccion.setText("Selecciona una accion a realizar:");
        jPanel1.add(jLabelSeleccionaAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 142, -1, -1));

        jPanelRegistrarActividades.setBackground(new java.awt.Color(42, 62, 169));
        jPanelRegistrarActividades.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelRegistrarActividadesMouseMoved(evt);
            }
        });
        jPanelRegistrarActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRegistrarActividadesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRegistrarActividadesMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N

        jLabelRegistrarActividades.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelRegistrarActividades.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarActividades.setText("Registrar actividades");

        javax.swing.GroupLayout jPanelRegistrarActividadesLayout = new javax.swing.GroupLayout(jPanelRegistrarActividades);
        jPanelRegistrarActividades.setLayout(jPanelRegistrarActividadesLayout);
        jPanelRegistrarActividadesLayout.setHorizontalGroup(
            jPanelRegistrarActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarActividadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegistrarActividades)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelRegistrarActividadesLayout.setVerticalGroup(
            jPanelRegistrarActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarActividadesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelRegistrarActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistrarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelRegistrarActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 211, -1, -1));

        jPanelConsultas.setBackground(new java.awt.Color(42, 62, 169));
        jPanelConsultas.setPreferredSize(new java.awt.Dimension(170, 49));
        jPanelConsultas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseMoved(evt);
            }
        });
        jPanelConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelConsultasMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N

        jLabelConsultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConsultas.setText("Consultas");

        javax.swing.GroupLayout jPanelConsultasLayout = new javax.swing.GroupLayout(jPanelConsultas);
        jPanelConsultas.setLayout(jPanelConsultasLayout);
        jPanelConsultasLayout.setHorizontalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jLabelConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelConsultasLayout.setVerticalGroup(
            jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 211, -1, -1));

        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés" }));
        jComboBoxIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdiomaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelSalirMouseClicked

    private void jPanelRegistrarActividadesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistrarActividadesMouseMoved
        jPanelRegistrarActividades.setBackground(new Color(67, 91, 220));
    }//GEN-LAST:event_jPanelRegistrarActividadesMouseMoved

    private void jPanelRegistrarActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistrarActividadesMouseExited
        jPanelRegistrarActividades.setBackground(new Color(42,62,169));
    }//GEN-LAST:event_jPanelRegistrarActividadesMouseExited

    private void jPanelConsultasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseMoved
        jPanelConsultas.setBackground(new Color(67, 91, 220));
    }//GEN-LAST:event_jPanelConsultasMouseMoved

    private void jPanelConsultasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseExited
        jPanelConsultas.setBackground(new Color(42,62,169));
    }//GEN-LAST:event_jPanelConsultasMouseExited

    private void jPanelRegistrarActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegistrarActividadesMouseClicked
     
        new RegistrarActividades(user, idiomaSistema).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanelRegistrarActividadesMouseClicked

    private void jPanelConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelConsultasMouseClicked
        this.dispose();
        new ConsultasSupervisor(user, idiomaSistema).setVisible(true);
    }//GEN-LAST:event_jPanelConsultasMouseClicked

    private void jComboBoxIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdiomaActionPerformed
        String itemSeleccionado = jComboBoxIdioma.getSelectedItem().toString();
        cambiarIdioma(itemSeleccionado);
    }//GEN-LAST:event_jComboBoxIdiomaActionPerformed

    public void cambiarIdioma(String idioma) {
        gestionIdiomas = new GestionIdiomas(idioma);
        jLabelBienvenido.setText(gestionIdiomas.getProperty("bienvenido"));
        jLabelLogout.setText(gestionIdiomas.getProperty("salir"));
        jLabelSeleccionaAccion.setText(gestionIdiomas.getProperty("selecciona_accion"));
        jLabelRegistrarActividades.setText(gestionIdiomas.getProperty("registrar_actividades"));
        jLabelConsultas.setText(gestionIdiomas.getProperty("consultas"));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxIdioma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelConsultas;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelNombreUser;
    private javax.swing.JLabel jLabelRegistrarActividades;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelSeleccionaAccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelConsultas;
    private javax.swing.JPanel jPanelRegistrarActividades;
    // End of variables declaration//GEN-END:variables

}
